version: "3"
services:
  influxdb_v2:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXD_HTTP_BIND_ADDRESS=:8086
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_center
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token

    command: influxd --reporting-disabled

  mosquitto:
    image: eclipse-mosquitto:2.0.10
    ports:
      - "1883:1883"
    volumes:
     - $PWD/app/server/mqtt/docker-mosquitto/mosquitto:/mosquitto/

  telegraf:
    image: telegraf:latest
    volumes:
      - $PWD/app/server/mqtt/telegraf-docker.conf:/etc/telegraf/telegraf.conf

  iot_center:
    image: node:12
    ports:
      - "5000:5000"
    environment:
      - INFLUX_URL=http://${EXTERNAL_IP}:8086
      - INFLUX_TOKEN=my-token
      - INFLUX_ORG=my-org
      - MQTT_TOPIC=iot_center
      - MQTT_URL=mqtt://${EXTERNAL_IP}:1883
    volumes:
      - $PWD/app:/app
    working_dir: /app
    command: ./run.sh
    depends_on:
      - influxdb_v2
      - mosquitto
